name: Build and Deploy to GKE

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DEPLOYMENT_NAME: angular-deployment
  IMAGE: gcr.io/${{ secrets.GKE_PROJECT }}/angular-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Authenticate Docker
      run: gcloud auth configure-docker --quiet

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Build Docker image
      run: docker build -t "$IMAGE:$GITHUB_SHA" .

    - name: Push Docker image
      run: docker push "$IMAGE:$GITHUB_SHA"

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/$DEPLOYMENT_NAME angular=$IMAGE:$GITHUB_SHA --record
        kubectl rollout status deployment/$DEPLOYMENT_NAME
